/**
 * Created by Michael on 10/26/2017.
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 *Completed on 10/27/17
 */
public class Problem2 {
    public static void main(String[] args) {
        // variables list
        int runningTotal =0,lastTerm = 1, middleTerm = 1, nextTerm = 2;
        int doNotExceed  = 4000000;

        while (nextTerm < doNotExceed){
            if(middleTerm%2 == 0){
                runningTotal = middleTerm+runningTotal;
            }
            nextTerm = middleTerm + lastTerm;
            lastTerm = middleTerm;
            middleTerm =nextTerm;
        }
        System.out.println("The total is " +runningTotal);

    }
}
